// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  site: 'https://icefall.dev',
  // Allow importing the canonical install.sh (repo root) into the docs via ?raw.
  vite: { server: { fs: { allow: ['..'] } } },
  integrations: [
    starlight({
      title: 'Icefall',
      description: 'A fast, simple, self-hosted deployment platform',
      social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/nord-forge/icefall' }],
      logo: { src: './src/assets/logo.svg' },
      customCss: ['./src/styles/custom.css'],
      components: {
        ThemeSelect: './src/components/ThemeSelect.astro',
      },
      editLink: { baseUrl: 'https://github.com/nord-forge/icefall/edit/main/website/' },
      sidebar: [
        {
          label: 'Getting Started',
          items: [
            { label: 'Introduction', slug: 'getting-started/introduction' },
            { label: 'Installation', slug: 'getting-started/installation' },
            { label: 'Quick Start', slug: 'getting-started/quick-start' },
          ],
        },
        {
          label: 'Core Concepts',
          items: [
            { label: 'Architecture', slug: 'concepts/architecture' },
            { label: 'How Builds Work', slug: 'concepts/builds' },
            { label: 'Deployments', slug: 'concepts/deployments' },
            { label: 'Environments', slug: 'concepts/environments' },
            { label: 'Networking', slug: 'concepts/networking' },
            { label: 'Domain Routing', slug: 'concepts/domains' },
            { label: 'Security', slug: 'concepts/security' },
            { label: 'Managed Databases', slug: 'concepts/databases' },
            { label: 'Multi-server', slug: 'concepts/multi-server' },
            { label: 'Container Runtime', slug: 'concepts/container-runtime' },
          ],
        },
        {
          label: 'Framework Guides',
          items: [
            { label: 'Astro', slug: 'frameworks/astro' },
            { label: 'Next.js', slug: 'frameworks/nextjs' },
            { label: 'React (Vite)', slug: 'frameworks/react' },
            { label: 'Vue', slug: 'frameworks/vue' },
            { label: 'Nuxt', slug: 'frameworks/nuxt' },
            { label: 'Node.js', slug: 'frameworks/nodejs' },
            { label: 'Dockerfile', slug: 'frameworks/dockerfile' },
            { label: 'Static Site', slug: 'frameworks/static' },
          ],
        },
        {
          label: 'Databases',
          items: [
            { label: 'Provisioning', slug: 'databases/provisioning' },
            { label: 'Backups & Restore', slug: 'databases/backups' },
          ],
        },
        {
          label: 'Monitoring',
          items: [
            { label: 'Health Checks', slug: 'monitoring/health-checks' },
            { label: 'Logs', slug: 'monitoring/logs' },
            { label: 'Metrics', slug: 'monitoring/metrics' },
          ],
        },
        {
          label: 'Authentication',
          items: [
            { label: 'Users & Roles', slug: 'auth/users' },
            { label: 'API Tokens', slug: 'auth/tokens' },
            { label: 'OAuth', slug: 'auth/oauth' },
          ],
        },
        {
          label: 'CLI Reference',
          items: [
            { label: 'Commands', slug: 'cli/commands' },
            { label: 'Configuration', slug: 'cli/configuration' },
          ],
        },
        {
          label: 'How-To Guides',
          items: [
            { label: 'Deploy from GitHub', slug: 'guides/deploy-from-github' },
            { label: 'Deploy from GitLab', slug: 'guides/deploy-from-gitlab' },
            { label: 'Deploy a Docker image', slug: 'guides/deploy-docker-image' },
            { label: 'Deploy a Compose stack', slug: 'guides/deploy-docker-compose' },
            { label: 'Deploy a static site', slug: 'guides/deploy-static-site' },
            { label: 'Deploy from a monorepo', slug: 'guides/deploy-monorepo' },
            { label: 'Override the build', slug: 'guides/custom-dockerfile' },
            { label: 'Preview environments', slug: 'guides/preview-environments' },
            { label: 'Roll back a deploy', slug: 'guides/rollback-deploy' },
            { label: 'Scheduled deploy', slug: 'guides/scheduled-deploy' },
            { label: 'Custom domain', slug: 'guides/custom-domain' },
            { label: 'Wildcard domains', slug: 'guides/wildcard-domain' },
            { label: 'Path routing', slug: 'guides/path-routing' },
            { label: 'Connect a database', slug: 'guides/connect-database' },
            { label: 'Back up and restore', slug: 'guides/backup-restore' },
            { label: 'Database browser', slug: 'guides/database-browser' },
            { label: 'External database', slug: 'guides/external-database' },
            { label: 'Add a server', slug: 'guides/add-server' },
            { label: 'Move an app', slug: 'guides/migrate-app' },
            { label: 'Server selection', slug: 'guides/server-selection' },
            { label: 'Enable 2FA', slug: 'guides/setup-2fa' },
            { label: 'GitHub OAuth', slug: 'guides/oauth-github' },
            { label: 'Google OAuth', slug: 'guides/oauth-google' },
            { label: 'API tokens', slug: 'guides/api-tokens' },
            { label: 'Invite team members', slug: 'guides/invite-users' },
            { label: 'Health checks', slug: 'guides/health-checks' },
            { label: 'Notifications', slug: 'guides/setup-notifications' },
            { label: 'Search logs', slug: 'guides/log-search' },
            { label: 'Log drains', slug: 'guides/log-drains' },
            { label: 'Deploy from the CLI', slug: 'guides/cli-deploy' },
            { label: 'Manage from the CLI', slug: 'guides/cli-management' },
            { label: 'Environment variables', slug: 'guides/environment-variables' },
            { label: 'Resource limits', slug: 'guides/resource-limits' },
            { label: 'Ghost Mode', slug: 'guides/ghost-mode' },
            { label: 'Update Icefall', slug: 'guides/self-update' },
            { label: 'Server migration', slug: 'guides/server-migration' },
            { label: 'Set up Podman', slug: 'guides/podman-setup' },
            { label: 'Migrate to Podman', slug: 'guides/podman-migration' },
            { label: 'Troubleshoot Podman', slug: 'guides/podman-troubleshooting' },
          ],
        },
        {
          label: 'MCP Integration',
          items: [
            { label: 'Overview (generic client)', slug: 'guides/mcp-generic' },
            { label: 'Claude Code', slug: 'guides/mcp-claude-code' },
            { label: 'Cursor', slug: 'guides/mcp-cursor' },
            { label: 'Windsurf', slug: 'guides/mcp-windsurf' },
          ],
        },
        {
          label: 'Migrating to Icefall',
          items: [
            { label: 'From Dokku', slug: 'guides/migrate-from-dokku' },
            { label: 'From CapRover', slug: 'guides/migrate-from-caprover' },
            { label: 'From Heroku', slug: 'guides/migrate-from-heroku' },
            { label: 'From Docker Compose', slug: 'guides/migrate-from-docker-compose' },
          ],
        },
        {
          label: 'API Reference',
          items: [
            { label: 'Overview', slug: 'api/overview' },
            { label: 'REST API', slug: 'api/rest' },
            { label: 'Apps', slug: 'api/apps' },
            { label: 'Deploys', slug: 'api/deploys' },
            { label: 'Databases', slug: 'api/databases' },
            { label: 'Domains', slug: 'api/domains' },
            { label: 'Environment Variables', slug: 'api/env-vars' },
            { label: 'Servers', slug: 'api/servers' },
            { label: 'Auth', slug: 'api/auth' },
            { label: 'Users', slug: 'api/users' },
            { label: 'API Tokens', slug: 'api/tokens' },
            { label: 'Notifications', slug: 'api/notifications' },
            { label: 'Settings', slug: 'api/settings' },
            { label: 'Webhooks', slug: 'api/webhooks' },
            { label: 'MCP Server', slug: 'api/mcp' },
            { label: 'MCP Tools Reference', slug: 'api/mcp-tools' },
          ],
        },
        {
          label: 'Server Management',
          items: [
            { label: 'Migration', slug: 'management/migration' },
            { label: 'Notifications', slug: 'management/notifications' },
            { label: 'Updates', slug: 'management/updates' },
          ],
        },
        {
          label: 'Troubleshooting',
          items: [
            { label: 'Deploy Failures', slug: 'troubleshooting/deploy-failures' },
            { label: 'Networking', slug: 'troubleshooting/networking' },
            { label: 'Databases', slug: 'troubleshooting/databases' },
            { label: 'Multi-server', slug: 'troubleshooting/multi-server' },
            { label: 'Performance', slug: 'troubleshooting/performance' },
            { label: 'Authentication', slug: 'troubleshooting/auth' },
            { label: 'Podman', slug: 'troubleshooting/podman' },
            { label: 'FAQ', slug: 'troubleshooting/faq' },
          ],
        },
        {
          label: 'Reference',
          items: [
            { label: 'Podman Runtime', slug: 'reference/podman' },
            { label: 'Podman Configuration', slug: 'reference/podman-config' },
            { label: 'Docker vs Podman', slug: 'reference/podman-differences' },
          ],
        },
      ],
    }),
  ],
});
